### PR TITLE
README is now a Rmd file

### LINKED ISSUE #86: Re-write readme
That is has a similar structure and content as the readme of eslqabsR

### PR DESCRIPTION
**Pull request by Felixmil**
resolve #86 

+ added dependencies remotes in DESCRIPTION

### CODE REVIEW

**Comment by Felixmil** [comment]
Maybe add a `Preview `or `Usage ` section to showcase what the package does.

**Comment by PavelBal** [comment]
This is good. I am finishing reviewing the vignette-PR. After a website with documentation has been built, we can add a "Learn more" section.

**Comment by PavelBal** [comment]
@Felixmil We have now finally merged two moster-PRs, and the readme was slightly changed in one of them. Could you please update? And then we can merge.

**Comment by Felixmil** [comment]
@PavelBal Main was merged into this branch and pkgdown website was rendered.

**Pull request merged**
